Repository wiris/html-integrations, pull requests merged in 2025-01, with the labels that each got.

#1071 Fix console error that lead to issues with insert formulas on react/vue
  packages/ckeditor5/dist/browser/index.js
  packages/ckeditor5/dist/browser/index.js.map
  packages/ckeditor5/dist/browser/index.umd.js
  packages/ckeditor5/dist/browser/index.umd.js.map
  packages/ckeditor5/dist/index.js
  packages/ckeditor5/dist/index.js.map
  packages/ckeditor5/src/plugin.js
Labels: type:bug, package:ckeditor5, tech:react, tech:vue

#1073 Create TinyMCE 7 demo
  .github/workflows/deploy-staging.yml
  demos/html/tinymce7/babel.config.js
  demos/html/tinymce7/index.html
  demos/html/tinymce7/package.json
  demos/html/tinymce7/project.json
  demos/html/tinymce7/src/app.js
  demos/html/tinymce7/src/static/style.css
  demos/html/tinymce7/webpack.config.js
  packages/tinymce7/README.md
  scripts/services/paths.json
  staging/branch/html/index.html
  staging/branch/index.html
Labels: type:enhancement

#995 Feat: Add a blacklist param for the latex and mathml detection. [VIEWER IMPROVEMENTS]
  packages/viewer/src/latex.ts
  packages/viewer/src/mathml.ts
  packages/viewer/src/properties.ts
Labels: package:viewer

#1056 fix: insert buttons are hidden on ipad
  demos/html/ckeditor5/src/app.js
  packages/ckeditor5/dist/browser/index-editor.css
  packages/ckeditor5/dist/browser/index.css
  packages/ckeditor5/dist/browser/index.css.map
  packages/ckeditor5/dist/browser/index.js
  packages/ckeditor5/dist/browser/index.js.map
  packages/ckeditor5/dist/browser/index.umd.js
  packages/ckeditor5/dist/browser/index.umd.js.map
  packages/ckeditor5/dist/index.js
  packages/ckeditor5/dist/index.js.map
  packages/devkit/src/modal.js
  packages/devkit/styles/styles.css
Labels: package:devkit, browser:chrome

#1076 fix: TinyMCE7 sanitization
  demos/html/tinymce7/src/app.js
  packages/tinymce7/README.md
Labels: type:bug

#1075 Take into account wiriseditorparselatex
  packages/viewer/docs/spec.md
  packages/viewer/src/latex.ts
  packages/viewer/src/properties.ts
Labels: type:bug

#1080 Create staging cleanup repo
  .github/workflows/staging-cleanup.yml
Labels: type:enhancement
